# Generated by Django 4.2.6 on 2024-02-06 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
            preserve_default=False,
        ),
    ]
