# Generated by Django 4.2.6 on 2024-02-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
