# Generated by Django 4.2.6 on 2024-02-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
    ]
