# Generated by Django 4.2.6 on 2024-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
