# Generated by Django 4.2.6 on 2024-02-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_payment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
    ]
